'use client';

import React, { useState } from 'react';
import { 
  Scale, 
  ShieldCheck, 
  Lock, 
  Radio, 
  PenTool, 
  Check, 
  X, 
  Award,
  Sparkles,
  Zap,
  Cpu
} from 'lucide-react';

export const ComparisonModule: React.FC = () => {
  const [selectedGoal, setSelectedGoal] = useState<'bulk_data' | 'legal_contracts' | 'remote_work' | 'code_signing'>('bulk_data');

  const comparisonCriteria = [
    {
      metric: 'Primary Security Goal',
      vpn: 'Confidentiality & Session Privacy',
      signature: 'Authenticity, Integrity & Non-Repudiation',
      winner: 'Context Dependent',
    },
    {
      metric: 'Underlying Cryptographic Model',
      vpn: 'Hybrid (PKE Handshake + Symmetric AES-GCM)',
      signature: 'Pure Asymmetric (SHA-256 Digest + RSA/ECDSA)',
      winner: 'Both High Security',
    },
    {
      metric: 'Performance & Bulk Data Overhead',
      vpn: 'Ultra Fast (Symmetric stream encryption ~1-2ms)',
      signature: 'Computationally heavier for large individual files',
      winner: 'VPN (for streaming throughput)',
    },
    {
      metric: 'Proof Against Deniability (Non-Repudiation)',
      vpn: 'Low (Shared session key can be generated by both sides)',
      signature: 'Absolute (Only sender has private key)',
      winner: 'Digital Signatures',
    },
    {
      metric: 'Protection Against Eavesdropping',
      vpn: 'Full (Hides endpoints, metadata & packet payload)',
      signature: 'None (Plaintext can remain unencrypted unless combined)',
      winner: 'VPN',
    },
    {
      metric: 'Implementation Complexity',
      vpn: 'Moderate (Requires tunnel interfaces & daemon setup)',
      signature: 'Low/Medium (API cryptographic call on message buffer)',
      winner: 'Digital Signatures',
    },
  ];

  const goalRecommendations = {
    bulk_data: {
      title: 'Bulk Data Transfer & Streaming',
      winner: 'VPN Encryption (TLS 1.3 / IPsec)',
      badge: 'VPN Best Suited',
      desc: 'VPNs use asymmetric PKE only during the initial handshake to exchange a symmetric key, then stream gigabytes of data using AES-GCM with hardware AES-NI acceleration, minimizing latency and CPU overhead.',
    },
    legal_contracts: {
      title: 'Legal Contracts & Financial Authorizations',
      winner: 'Digital Signatures (RSA-PSS / ECDSA)',
      badge: 'Signatures Best Suited',
      desc: 'Digital signatures bind a document cryptographically to the signer’s private key. In legal disputes, the signer cannot deny sending the file (Non-Repudiation), which a VPN session key cannot guarantee.',
    },
    remote_work: {
      title: 'Secure Remote Work & Enterprise Access',
      winner: 'VPN Encryption (IPsec / OpenVPN / WireGuard)',
      badge: 'VPN Best Suited',
      desc: 'VPNs establish an encrypted perimeter tunnel between remote employees and corporate intranets, shielding all DNS queries, web requests, and internal databases from local LAN sniffers and rogue Wi-Fi hotspots.',
    },
    code_signing: {
      title: 'Software Updates & Code Signing',
      winner: 'Digital Signatures (Authenticode / GPG)',
      badge: 'Signatures Best Suited',
      desc: 'Distributing software over public CDNs requires end users to verify that binaries originated from the authentic vendor and were not infected by malware or tampered with by an MITM cache.',
    },
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header Banner */}
      <div className="glass-panel rounded-3xl p-6 sm:p-7 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border border-emerald-500/20 shadow-2xl">
        <div className="flex items-center space-x-3.5">
          <div className="p-3.5 rounded-2xl bg-emerald-950/80 border border-emerald-500/40 text-emerald-400 shadow-lg shadow-emerald-500/10">
            <Scale className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-black text-white flex items-center gap-2">
              Cryptographic Comparison & Analysis Module
              <span className="text-[10px] px-2.5 py-0.5 rounded-full bg-emerald-950/80 text-emerald-300 border border-emerald-700 font-mono font-bold">
                SRS 1.6 vii
              </span>
            </h2>
            <p className="text-xs text-zinc-400 font-medium">
              Evaluating VPN Encryption vs. Digital Signatures across Performance Overhead, Confidentiality, Authenticity, and Complexity.
            </p>
          </div>
        </div>
      </div>

      {/* Goal Decision Matrix */}
      <div className="glass-panel rounded-3xl p-6 sm:p-7 border border-white/10 shadow-2xl space-y-5">
        <div className="flex items-center justify-between border-b border-white/10 pb-3">
          <div className="flex items-center space-x-2">
            <Award className="w-4 h-4 text-emerald-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              Security Goal Decision Matrix
            </h3>
          </div>
          <span className="text-xs text-zinc-400 font-medium">Select an operational scenario to evaluate:</span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { id: 'bulk_data' as const, label: 'Bulk Streaming', icon: <Cpu className="w-4 h-4" /> },
            { id: 'legal_contracts' as const, label: 'Contracts & Approvals', icon: <PenTool className="w-4 h-4" /> },
            { id: 'remote_work' as const, label: 'Remote Access / VPN', icon: <Radio className="w-4 h-4" /> },
            { id: 'code_signing' as const, label: 'Software Updates', icon: <ShieldCheck className="w-4 h-4" /> },
          ].map((goal) => (
            <button
              key={goal.id}
              onClick={() => setSelectedGoal(goal.id)}
              className={`p-3.5 rounded-2xl flex items-center space-x-3 text-xs font-bold border transition-all active:scale-95 ${
                selectedGoal === goal.id
                  ? 'bg-gradient-to-r from-emerald-500 to-teal-500 text-slate-950 shadow-lg shadow-emerald-500/20 border-emerald-400'
                  : 'glass-pill text-zinc-400 hover:text-white hover:bg-white/[0.08]'
              }`}
            >
              {goal.icon}
              <span className="truncate">{goal.label}</span>
            </button>
          ))}
        </div>

        {/* Selected Recommendation Card */}
        <div className="p-5 rounded-2xl bg-black/60 border border-white/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-inner">
          <div className="space-y-1.5">
            <div className="flex items-center space-x-2.5">
              <span className="text-sm font-bold text-white">{goalRecommendations[selectedGoal].title}:</span>
              <span className="px-2.5 py-0.5 rounded-full bg-emerald-950 text-emerald-300 text-[10px] font-mono font-bold border border-emerald-800">
                {goalRecommendations[selectedGoal].badge}
              </span>
            </div>
            <p className="text-xs text-zinc-300 leading-relaxed max-w-3xl font-sans">
              {goalRecommendations[selectedGoal].desc}
            </p>
          </div>
          <div className="p-3.5 rounded-xl bg-emerald-950/80 border border-emerald-500/40 text-xs font-mono text-emerald-300 font-bold shrink-0 shadow-md">
            {goalRecommendations[selectedGoal].winner}
          </div>
        </div>
      </div>

      {/* Side-by-Side Detailed Comparison Table */}
      <div className="glass-panel rounded-3xl p-6 sm:p-7 border border-white/10 shadow-2xl space-y-4">
        <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2">
          <Scale className="w-4 h-4 text-emerald-400" />
          Multi-Metric Comparison Matrix
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left border-collapse">
            <thead>
              <tr className="border-b border-white/10 text-zinc-400 uppercase text-[10px] font-mono">
                <th className="py-3.5 px-4">Evaluation Metric</th>
                <th className="py-3.5 px-4 text-emerald-400">VPN Encryption (TLS / IPsec)</th>
                <th className="py-3.5 px-4 text-purple-400">Digital Signatures (RSA / PSS)</th>
                <th className="py-3.5 px-4 text-teal-400">Advantage / Better Fit</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 font-sans">
              {comparisonCriteria.map((row, idx) => (
                <tr key={idx} className="hover:bg-white/[0.03] transition-colors">
                  <td className="py-3.5 px-4 font-bold text-white">{row.metric}</td>
                  <td className="py-3.5 px-4 text-zinc-300">{row.vpn}</td>
                  <td className="py-3.5 px-4 text-zinc-300">{row.signature}</td>
                  <td className="py-3.5 px-4 font-mono font-bold text-emerald-300">{row.winner}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
